-- ========================================
-- Dayopt - 開発用シードデータ
-- ========================================
-- このファイルは `supabase db reset` 実行時に自動的に読み込まれます。
--
-- 全テーブルが RLS + user_id 必須のため、認証なしでのシードは制限されます。
-- サインアップ後、アプリケーション上でデータを作成してください。
--
-- Preview Supabase のリセット:
--   npm run db:reset-preview  (Phase 3 で追加予定)
--
-- ========================================
-- デフォルトのシステム設定
-- ========================================

-- notification_preferences のデフォルト値はアプリ側で作成されるため、
-- ここでは挿入不要。

-- ========================================
-- 手動シード用テンプレート（SQL Editor で実行）
-- ========================================
-- サインアップ済みユーザーに対して手動でテストデータを追加する場合:
--
-- -- タグ作成
-- INSERT INTO tags (user_id, name, color)
-- VALUES (auth.uid(), '仕事', '#3B82F6'),
--        (auth.uid(), '個人', '#10B981'),
--        (auth.uid(), '学習', '#F59E0B');
--
-- -- プラン作成
-- INSERT INTO plans (user_id, title, status, priority, scheduled_date, start_time, end_time)
-- VALUES
--   (auth.uid(), 'サンプルタスク', 'active', 'normal', CURRENT_DATE, '09:00', '10:00'),
--   (auth.uid(), '午後の作業', 'backlog', 'high', CURRENT_DATE, '14:00', '16:00');
