// @generated by scripts/tasks/sync-auth-email-templates.ts
// Source of truth: supabase/functions/send-auth-email/. Do not edit this file directly.

/**
 * Email Confirmation Template
 * 新規登録時のメールアドレス確認メール
 *
 * Supabase Auth の signup フローで使用
 */

import { Body, Button, Container, Head, Html, Link, Section, Text } from 'react-email';

import * as styles from './auth-email-styles.generated';

type Locale = 'en' | 'ja';

const i18n = {
  en: {
    heading: 'Confirm your email',
    greeting: (name: string) => (name ? `Hi ${name},` : 'Hi there,'),
    body: 'Thanks for signing up for Dayopt. Please confirm your email address by clicking the button below.',
    ctaButton: 'Confirm Email Address',
    buttonFallback: "If the button doesn't work, copy and paste this link into your browser:",
    ignoreLine: (_appUrl: string) =>
      `If you didn't create an account on Dayopt, you can safely ignore this email.`,
    teamSignature: 'The Dayopt Team',
  },
  ja: {
    heading: 'メールアドレスの確認',
    greeting: (name: string) => (name ? `${name}さん、こんにちは。` : 'こんにちは。'),
    body: 'Dayopt にご登録いただきありがとうございます。以下のボタンをクリックして、メールアドレスを確認してください。',
    ctaButton: 'メールアドレスを確認',
    buttonFallback:
      'ボタンが機能しない場合は、以下のリンクをブラウザにコピー＆ペーストしてください：',
    ignoreLine: (_appUrl: string) =>
      'Dayopt でアカウントを作成した覚えがない場合は、このメールを無視してください。',
    teamSignature: 'Dayopt チーム',
  },
} as const;

export interface ConfirmEmailProps {
  userName: string;
  confirmUrl: string;
  locale?: Locale;
  appUrl?: string;
}

export function ConfirmEmail({
  userName,
  confirmUrl,
  locale = 'en',
  appUrl = 'https://app.dayopt.app',
}: ConfirmEmailProps) {
  const t = i18n[locale];
  return (
    <Html>
      <Head />
      <Body style={styles.main}>
        <Container style={styles.container}>
          <Section style={styles.section}>
            <Text style={styles.heading}>{t.heading}</Text>
            <Text style={styles.paragraph}>{t.greeting(userName)}</Text>
            <Text style={styles.paragraph}>{t.body}</Text>
            <Button style={styles.button} href={confirmUrl}>
              {t.ctaButton}
            </Button>
            <Text style={styles.smallText}>{t.buttonFallback}</Text>
            <Text style={{ ...styles.smallText, wordBreak: 'break-all' }}>
              <Link style={styles.link} href={confirmUrl}>
                {confirmUrl}
              </Link>
            </Text>
            <Text style={styles.footer}>
              {t.ignoreLine(appUrl)}
              <br />
              <br />
              {t.teamSignature}
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

export default ConfirmEmail;
