// @generated by scripts/sync-auth-email-templates.ts
// Source of truth: supabase/functions/send-auth-email/. Do not edit this file directly.

/**
 * Email Change Confirmation Template
 * メールアドレス変更時の確認メール
 *
 * Supabase Auth の email_change フローで使用。
 * Secure Email Change 有効時は現アドレス・新アドレスの両方へ送る 2 バリアント構成:
 * - variant 'current': 現アドレス宛（変更リクエストの承認）
 * - variant 'new':     新アドレス宛（新アドレスの確認）
 */

import { Body, Button, Container, Head, Html, Link, Section, Text } from 'react-email';

import * as styles from './auth-email-styles.generated';

type Locale = 'en' | 'ja';
type Variant = 'current' | 'new';

const i18n = {
  en: {
    current: {
      heading: 'Approve your email change',
      body: (newEmail: string) =>
        `We received a request to change your Dayopt account email to ${newEmail}. To approve this change, click the button below.`,
      ctaButton: 'Approve Email Change',
      ignoreLine:
        "If you didn't request this change, you can ignore this email. Your email address will not change. We also recommend changing your password.",
    },
    new: {
      heading: 'Confirm your new email',
      body: () =>
        'We received a request to use this address as the new email for your Dayopt account. To confirm, click the button below.',
      ctaButton: 'Confirm New Email Address',
      ignoreLine: "If you didn't request this change, you can safely ignore this email.",
    },
    greeting: (name: string) => (name ? `Hi ${name},` : 'Hi there,'),
    buttonFallback: "If the button doesn't work, copy and paste this link into your browser:",
    teamSignature: 'The Dayopt Team',
  },
  ja: {
    current: {
      heading: 'メールアドレス変更の承認',
      body: (newEmail: string) =>
        `Dayopt アカウントのメールアドレスを ${newEmail} に変更するリクエストを受け付けました。この変更を承認するには、以下のボタンをクリックしてください。`,
      ctaButton: 'メールアドレス変更を承認',
      ignoreLine:
        '心当たりがない場合は、このメールを無視してください。メールアドレスは変更されません。あわせてパスワードの変更をおすすめします。',
    },
    new: {
      heading: '新しいメールアドレスの確認',
      body: () =>
        'このアドレスを Dayopt アカウントの新しいメールアドレスにするリクエストを受け付けました。確認するには、以下のボタンをクリックしてください。',
      ctaButton: '新しいメールアドレスを確認',
      ignoreLine: '心当たりがない場合は、このメールを無視してください。',
    },
    greeting: (name: string) => (name ? `${name}さん、こんにちは。` : 'こんにちは。'),
    buttonFallback:
      'ボタンが機能しない場合は、以下のリンクをブラウザにコピー＆ペーストしてください：',
    teamSignature: 'Dayopt チーム',
  },
} as const;

export interface EmailChangeEmailProps {
  userName: string;
  confirmUrl: string;
  newEmail: string;
  variant: Variant;
  locale?: Locale;
}

export function EmailChangeEmail({
  userName,
  confirmUrl,
  newEmail,
  variant,
  locale = 'en',
}: EmailChangeEmailProps) {
  const t = i18n[locale];
  const tv = t[variant];
  return (
    <Html>
      <Head />
      <Body style={styles.main}>
        <Container style={styles.container}>
          <Section style={styles.section}>
            <Text style={styles.heading}>{tv.heading}</Text>
            <Text style={styles.paragraph}>{t.greeting(userName)}</Text>
            <Text style={styles.paragraph}>{tv.body(newEmail)}</Text>
            <Button style={styles.button} href={confirmUrl}>
              {tv.ctaButton}
            </Button>
            <Text style={styles.smallText}>{t.buttonFallback}</Text>
            <Text style={{ ...styles.smallText, wordBreak: 'break-all' }}>
              <Link style={styles.link} href={confirmUrl}>
                {confirmUrl}
              </Link>
            </Text>
            <Text style={styles.footer}>
              {tv.ignoreLine}
              <br />
              <br />
              {t.teamSignature}
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

export default EmailChangeEmail;
