/**
 * OG fallback画像(静的PNG)の生成スクリプト
 *
 * `apps/web/src/app/api/og/route.tsx` の fallback応答は元々
 * global quota超過時・rate limit backend障害時に `ImageResponse`(Satori)で
 * 動的レンダリングしていたが、fallback自体がcompute costを発生させ続ける
 * 問題があった(#2052)。このscriptは同じJSX・同じ見た目を**一度だけ**
 * Satoriでレンダリングし、結果を2箇所に出力する:
 *
 * 1. `public/og-fallback.png` — PRで目視レビューできる実体
 * 2. `src/app/api/og/og-fallback-image.generated.ts` — edge runtimeは
 *    リクエスト時に`fs`でpublicを読めないため、同じbyte列をbase64定数として
 *    route.tsxへ埋め込む(fetchでpublicを取りに行く追加ホップも作らない)
 *
 * デザインを変更する場合は、このscriptと route.tsx 側の見た目定義
 * (OG_COLORS.background背景 + dayoptBrand.name中央表示)を両方直し、
 * 再実行して両方の出力を再生成する。
 *
 * 使用方法: pnpm --filter @dayopt/web generate:og-fallback
 */

import { dayoptBrand } from '@dayopt/config';
import { OG_COLORS } from '@dayopt/foundations/og-colors';
import { execFileSync } from 'child_process';
import fs from 'fs';
import { ImageResponse } from 'next/og';
import path from 'path';

const PNG_OUTPUT_PATH = path.join(process.cwd(), 'public', 'og-fallback.png');
const MODULE_OUTPUT_PATH = path.join(
  process.cwd(),
  'src/app/api/og/og-fallback-image.generated.ts',
);

async function main() {
  const response = new ImageResponse(
    <div
      style={{
        height: '100%',
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: OG_COLORS.background,
      }}
    >
      <div style={{ display: 'flex', fontSize: 40, fontWeight: 500, color: OG_COLORS.foreground }}>
        {dayoptBrand.name}
      </div>
    </div>,
    { width: 1200, height: 630 },
  );

  const buffer = Buffer.from(await response.arrayBuffer());
  fs.writeFileSync(PNG_OUTPUT_PATH, buffer);
  console.log(`wrote ${buffer.byteLength} bytes to ${PNG_OUTPUT_PATH}`);

  const moduleSource = `// AUTO-GENERATED by \`pnpm --filter @dayopt/web generate:og-fallback\`. Do not edit by hand.
// 元データ: apps/web/public/og-fallback.png (1200x630 PNG, ${dayoptBrand.name}中央表示)。
// route.tsx はedge runtimeでpublicをfsで読めないため、このbase64定数を直接埋め込んでいる。
export const OG_FALLBACK_IMAGE_BASE64 = '${buffer.toString('base64')}';
`;
  fs.writeFileSync(MODULE_OUTPUT_PATH, moduleSource);
  console.log(`wrote ${moduleSource.length} chars to ${MODULE_OUTPUT_PATH}`);

  // 生ファイル書き込みはprettier未適用のため、format:checkとの差分を残さないよう
  // 生成直後にformatする(手動フォローアップをこのscriptの責務にする)。
  execFileSync('pnpm', ['exec', 'prettier', '--write', MODULE_OUTPUT_PATH], {
    stdio: 'inherit',
  });
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
