-- ============================================================
-- 関数一覧（読み物用 — CLIでは使用しない）
-- ============================================================
-- 最終同期日: 2026-07-13
-- 同期対象 migration:
--   - 20260415000000_inline_entry_tag_id.sql
--   - 20260424000000_restore_tag_parent_hierarchy.sql
--   - 20260425130000_merge_tags_with_hierarchy_auth_guard.sql
--   - 20260514000918_mcp_phase_1_5.sql
--   - 20260604230607_harden_function_execute_privileges.sql
--   - 20260610000000_entry_auto_record_model.sql
--   - 20260613000000_drop_orphan_tag_detail_rpcs.sql
--   - 20260615000000_drop_unused_stats_rpcs.sql
--   - 20260616000000_rename_duration_to_planned_duration.sql
--   - 20260712212527_records_table_and_drop_entries.sql
--   - 20260713120023_drop_time_model_compatibility_layer.sql
-- 全 app-facing 関数は authenticated に明示 GRANT。
-- PUBLIC/anon への関数 EXECUTE は revoke 済み。
-- ============================================================

-- ■ トリガー関数
--   update_updated_at()                       — 汎用 updated_at 自動更新
--   handle_new_user()                         — auth.users INSERT → profiles 自動作成
--   check_tag_hierarchy()                     — tags の root -> child 最大2階層を強制
--   check_tag_has_children()                  — active child を持つ tag の child 化を禁止
-- ■ RPC 関数
--   update_personalization(user_id, key, value) — user_settings.personalization 更新
--   merge_tags_with_hierarchy(user_id, source, target) — plans / records 対応の atomic タグマージ
--   batch_reorder_tags_hierarchy(user_id, tag_ids, parent_ids, sort_orders) — 階層 + 並び順更新
--   batch_rename_tags(user_id, tag_ids, names) — 複数タグ名を一括変更
--   rename_tag_group(user_id, old_name, new_name) — root tag group の名称変更
--   use_recovery_code(user_id, code_hash)     — MFAリカバリーコードを使用済みにマーク
--   count_unused_recovery_codes(user_id)      — 未使用リカバリーコード数
--   soft_delete_plan / restore_plan            — Plan の soft delete / restore
--   soft_delete_record / restore_record        — Record の soft delete / restore
--   confirm_day_plans_to_records(...)          — 完了 Plan を Record として一括確定
--   issue_oauth_token_pair(...)               — refresh/access token pair を service-role 経由で発行

-- ■ 削除済み RPC
--   get_tag_cumulative_time / get_tag_avg_fulfillment / get_tag_plan_rate /
--   get_tag_fulfillment_distribution / get_tag_hourly_distribution /
--   get_tag_dow_distribution / get_child_tag_breakdown /
--   get_tag_accuracy_trend / get_tag_recent_entries
--     -> 20260613000000_drop_orphan_tag_detail_rpcs.sql
--   get_energy_map / get_context_switches / get_cumulative_time /
--   get_plan_rate / get_avg_fulfillment
--     -> 20260615000000_drop_unused_stats_rpcs.sql
--   entries 系 CRUD / stats / backfill RPC
--     -> 20260712212527_records_table_and_drop_entries.sql
--   soft_delete_log / restore_log / confirm_day_plans_to_logs
--     -> 20260713120023_drop_time_model_compatibility_layer.sql
