-- ============================================================
-- 関数一覧（読み物用 — CLIでは使用しない）
-- ============================================================
-- 最終同期日: 2026-07-26
-- 同期対象 migration:
--   - 20260415000000_inline_entry_tag_id.sql
--   - 20260424000000_restore_tag_parent_hierarchy.sql
--   - 20260425130000_merge_tags_with_hierarchy_auth_guard.sql
--   - 20260514000918_mcp_phase_1_5.sql
--   - 20260604230607_harden_function_execute_privileges.sql
--   - 20260610000000_entry_auto_record_model.sql
--   - 20260613000000_drop_orphan_tag_detail_rpcs.sql
--   - 20260615000000_drop_unused_stats_rpcs.sql
--   - 20260616000000_rename_duration_to_planned_duration.sql
--   - 20260712212527_records_table_and_drop_entries.sql
--   - 20260713120023_drop_time_model_compatibility_layer.sql
--   - 20260726013339_mcp_environment_identity.sql
--   - 20260726015311_mcp_environment_authority_binding.sql
--   - 20260726021453_fix_mcp_environment_legacy_binding.sql
--   - 20260726033000_expand_user_data_purge_generation.sql
--   - 20260726033100_fix_user_data_purge_lock_order.sql
--   - 20260726040100_add_external_authority_maintenance.sql
--   - 20260726040200_harden_calendar_revoke_expiry.sql
--   - 20260726040300_allow_multiple_calendar_revoke_tokens.sql
--   - 20260726040400_align_external_authority_status.sql
--   - 20260726040500_rotate_or_enqueue_calendar_refresh_token.sql
--   - 20260726040600_make_calendar_token_rotation_idempotent.sql
-- ユーザー操作向け関数は authenticated、OAuth基盤関数はservice_roleへ
-- 必要なsignatureだけ明示GRANT。PUBLIC/anonへのEXECUTEはrevoke済み。
-- ============================================================

-- ■ トリガー関数
--   update_updated_at()                       — 汎用 updated_at 自動更新
--   handle_new_user()                         — auth.users INSERT → profiles 自動作成
--   check_tag_hierarchy()                     — tags の root -> child 最大2階層を強制
--   check_tag_has_children()                  — active child を持つ tag の child 化を禁止
-- ■ RPC 関数
--   update_personalization(user_id, key, value) — user_settings.personalization 更新
--   merge_tags_with_hierarchy(user_id, source, target) — plans / records 対応の atomic タグマージ
--   batch_reorder_tags_hierarchy(user_id, tag_ids, parent_ids, sort_orders) — 階層 + 並び順更新
--   batch_rename_tags(user_id, tag_ids, names) — 複数タグ名を一括変更
--   rename_tag_group(user_id, old_name, new_name) — root tag group の名称変更
--   use_recovery_code(user_id, code_hash)     — MFAリカバリーコードを使用済みにマーク
--   count_unused_recovery_codes(user_id)      — 未使用リカバリーコード数
--   soft_delete_plan / restore_plan            — Plan の soft delete / restore
--   soft_delete_record / restore_record        — Record の soft delete / restore
--   confirm_day_plans_to_records(...)          — 完了 Plan を Record として一括確定
--   get_mcp_environment_identity_v1()          — DB固有のOAuth/MCP identityをservice-roleへ返す
--   provision_mcp_environment_identity_v1(...) — data-less DBのidentityを一度だけ固定
--   create_oauth_authorization_grant_v2(...)   — identity-bound connection/codeをatomic発行
--   exchange_oauth_authorization_code_v2(...)  — code消費とtoken pair発行をatomic実行
--   rotate_oauth_refresh_token_v2(...)         — connection-bound refresh rotation/reuse検知
--   issue_oauth_token_pair(...)                — 旧caller drain中だけ残すread-only互換issuer
--   get_user_data_generation_v1(...)           — 現在のaccount-preserving purge世代
--   save_calendar_connection_command_v1(...)   — 世代再検証つきCalendar connection保存
--   rotate_or_enqueue_calendar_refresh_token_command_v2(...) — rotationを冪等CAS保存またはpurge後outboxへ退避
--   delete_all_user_data_command_v3(...)       — 世代更新、外部authority失効、全domain data削除
--   claim/complete/retry_calendar_revoke_outbox_v1(...) — 暗号化tokenのlease付きprovider失効
--   expire_calendar_revoke_outbox_v1(...)      — 期限切れ暗号文のbounded削除
--   cleanup_oauth_*_v1(...)                    — code/token/connectionの期限別bounded削除
--   cleanup_integration_security_events_v1(...) — payload-free eventの90日削除
--   get_external_authority_maintenance_status_v1() — IDを含まないbacklog集計

-- ■ 削除済み RPC
--   get_tag_cumulative_time / get_tag_avg_fulfillment / get_tag_plan_rate /
--   get_tag_fulfillment_distribution / get_tag_hourly_distribution /
--   get_tag_dow_distribution / get_child_tag_breakdown /
--   get_tag_accuracy_trend / get_tag_recent_entries
--     -> 20260613000000_drop_orphan_tag_detail_rpcs.sql
--   get_energy_map / get_context_switches / get_cumulative_time /
--   get_plan_rate / get_avg_fulfillment
--     -> 20260615000000_drop_unused_stats_rpcs.sql
--   entries 系 CRUD / stats / backfill RPC
--     -> 20260712212527_records_table_and_drop_entries.sql
--   soft_delete_log / restore_log / confirm_day_plans_to_logs
--     -> 20260713120023_drop_time_model_compatibility_layer.sql
