import { describe, expect, it } from 'vitest';

import {
  generateCredits,
  generateNoticesFile,
  getProductionDependencyFilter,
  normalizeGeneratedFileForCheck,
  parsePnpmLicenses,
} from '../license-generator';

describe('getProductionDependencyFilter', () => {
  it('includes workspace package dependencies in the pnpm license scan', () => {
    expect(getProductionDependencyFilter('@dayopt/product')).toBe('@dayopt/product...');
  });
});

describe('parsePnpmLicenses', () => {
  it('expands pnpm license groups into per-version package records', () => {
    const packages = parsePnpmLicenses(
      JSON.stringify({
        MIT: [
          {
            name: 'react',
            versions: ['19.2.7'],
            paths: [],
            license: 'MIT',
            author: 'Meta',
            homepage: 'https://react.dev',
          },
          {
            name: '@scope/shared',
            versions: ['1.0.0', '1.1.0'],
            paths: [],
            license: 'MIT',
          },
        ],
        '0BSD': [
          {
            name: 'tslib',
            versions: ['2.8.1'],
            paths: [],
            license: '0BSD',
            author: 'Microsoft Corp.',
            homepage: 'https://www.typescriptlang.org/',
          },
        ],
      }),
    );

    expect(Object.keys(packages)).toEqual([
      'react@19.2.7',
      '@scope/shared@1.0.0',
      '@scope/shared@1.1.0',
      'tslib@2.8.1',
    ]);
    expect(packages['tslib@2.8.1']).toMatchObject({
      licenses: '0BSD',
      publisher: 'Microsoft Corp.',
      repository: 'https://www.typescriptlang.org/',
    });

    expect(generateCredits(packages)).toEqual([
      {
        name: '@scope/shared',
        version: '1.0.0',
        license: 'MIT',
      },
      {
        name: '@scope/shared',
        version: '1.1.0',
        license: 'MIT',
      },
      {
        name: 'react',
        version: '19.2.7',
        license: 'MIT',
        repository: 'https://react.dev',
        publisher: 'Meta',
      },
      {
        name: 'tslib',
        version: '2.8.1',
        license: '0BSD',
        repository: 'https://www.typescriptlang.org/',
        publisher: 'Microsoft Corp.',
      },
    ]);
  });

  it('rejects malformed pnpm license entries', () => {
    expect(() =>
      parsePnpmLicenses(
        JSON.stringify({
          MIT: [
            {
              name: 'missing-version',
              license: 'MIT',
            },
          ],
        }),
      ),
    ).toThrow('versions');
  });
});

describe('generateNoticesFile', () => {
  it('does not include wall-clock timestamps', () => {
    const content = generateNoticesFile([], 'scripts/generate-licenses.ts');

    expect(content).toContain('Generated by scripts/generate-licenses.ts.');
    expect(content).not.toMatch(/Generated: \d{4}-\d{2}-\d{2}/);
  });

  it('labels the generating script per caller', () => {
    const content = generateNoticesFile([], 'apps/web/scripts/generate-licenses.ts');

    expect(content).toContain('Generated by apps/web/scripts/generate-licenses.ts.');
  });
});

describe('normalizeGeneratedFileForCheck', () => {
  it('ignores platform-specific native optional credits during drift checks', () => {
    const linuxCredits = `${JSON.stringify(
      [
        {
          name: '@next/swc-linux-x64-gnu',
          version: '16.2.9',
          license: 'MIT',
        },
        {
          name: '@tailwindcss/oxide-linux-x64-gnu',
          version: '4.3.3',
          license: 'MIT',
        },
        {
          name: 'lightningcss-linux-x64-gnu',
          version: '1.30.2',
          license: 'MPL-2.0',
        },
        {
          name: 'react',
          version: '19.2.7',
          license: 'MIT',
        },
      ],
      null,
      2,
    )}\n`;
    const darwinCredits = `${JSON.stringify(
      [
        {
          name: '@next/swc-darwin-arm64',
          version: '16.2.9',
          license: 'MIT',
        },
        {
          name: '@tailwindcss/oxide-darwin-arm64',
          version: '4.3.3',
          license: 'MIT',
        },
        {
          name: 'lightningcss-darwin-arm64',
          version: '1.30.2',
          license: 'MPL-2.0',
        },
        {
          name: 'fsevents',
          version: '2.3.3',
          license: 'MIT',
        },
        {
          name: 'react',
          version: '19.2.7',
          license: 'MIT',
        },
      ],
      null,
      2,
    )}\n`;

    expect(normalizeGeneratedFileForCheck('oss-credits.json', darwinCredits)).toBe(
      normalizeGeneratedFileForCheck('oss-credits.json', linuxCredits),
    );
  });
});
