/** tRPCエラーコードの型定義 */
export type TRPCErrorCode =
  | 'INTERNAL_SERVER_ERROR'
  | 'NOT_FOUND'
  | 'BAD_REQUEST'
  | 'FORBIDDEN'
  | 'UNAUTHORIZED'
  | 'CONFLICT'
  | 'CLIENT_CLOSED_REQUEST'
  | 'TIMEOUT';

/** サービスエラーコードとtRPCエラーコードのマッピング。 */
export const ERROR_CODE_MAP: Record<string, TRPCErrorCode> = {
  // ===== 共通エラー =====
  FETCH_FAILED: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CREATE_FAILED: 'INTERNAL_SERVER_ERROR',
  UPDATE_FAILED: 'INTERNAL_SERVER_ERROR',
  DELETE_FAILED: 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED: 'BAD_REQUEST',
  INVALID_INPUT: 'BAD_REQUEST',
  RANGE_TOO_DENSE: 'BAD_REQUEST',
  CONTEXT_CHANGED: 'CONFLICT',
  REQUEST_CANCELLED: 'CLIENT_CLOSED_REQUEST',
  READ_TIMEOUT: 'TIMEOUT',

  // ===== 認証・認可エラー =====
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  // 再認証の資格情報が違う（削除フローのパスワード / TOTP）。UNAUTHORIZED にすると
  // query-client の isAuthError が session 失効とみなしてログイン画面へ飛ばし、
  // 「パスワードが正しくありません」がユーザーに届かない。request 自体は認証済みなので
  // FORBIDDEN が正しい（#1925）
  INVALID_PASSWORD: 'FORBIDDEN',
  // 再認証手段そのものが使えない（#1925）。EXPECTED_TRPC_CODES に載る code へ写像し、
  // handleServiceError 側で Sentry へ二重報告されるのを避ける（報告は呼び出し側の canary 1 本）
  REAUTH_UNAVAILABLE: 'BAD_REQUEST',
  // メールアドレス変更の GoTrue updateUser 失敗（衝突等）。ユーザー起因の想定内失敗なので
  // BAD_REQUEST（EXPECTED_TRPC_CODES に含まれ、handleServiceError の自動 Sentry 報告対象外）
  EMAIL_UPDATE_FAILED: 'BAD_REQUEST',
  RECOVERY_EXHAUSTED: 'BAD_REQUEST',
  RECOVERY_INVALID: 'BAD_REQUEST',
  RECOVERY_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Tag関連 =====
  DUPLICATE_NAME: 'BAD_REQUEST',
  MERGE_FAILED: 'INTERNAL_SERVER_ERROR',
  SAME_TAG_MERGE: 'BAD_REQUEST',
  TAG_ARCHIVED: 'BAD_REQUEST',
  TARGET_NOT_FOUND: 'NOT_FOUND',
  UNGROUP_CONFLICTS: 'BAD_REQUEST',
  GROUP_NAME_CONFLICT: 'BAD_REQUEST',

  // ===== Tag並び替え関連 =====
  REORDER_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Palette関連 =====
  PIN_FAILED: 'INTERNAL_SERVER_ERROR',
  UNPIN_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== History関連 =====
  FETCH_PINNED_FAILED: 'INTERNAL_SERVER_ERROR',
  FETCH_ENTRIES_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Entry関連 =====
  TAG_FILTER_FAILED: 'INTERNAL_SERVER_ERROR',
  TIME_OVERLAP: 'BAD_REQUEST',
  UNPLANNED_IN_FUTURE: 'BAD_REQUEST',
  RECORD_IN_FUTURE: 'BAD_REQUEST',
  ALREADY_RECORDED: 'BAD_REQUEST',
  PLAN_IN_PAST: 'BAD_REQUEST',
  PLAN_TIME_LOCKED: 'BAD_REQUEST',
  SKIP_IN_FUTURE: 'BAD_REQUEST',
  INVALID_TIME_RANGE: 'BAD_REQUEST',
  INVALID_ENTRY_SHAPE: 'BAD_REQUEST',
  RESTORE_FAILED: 'INTERNAL_SERVER_ERROR',
  CONFLICT: 'CONFLICT',
  STALE_VERSION: 'CONFLICT',
  STALE_TARGET: 'CONFLICT',
  RETRYABLE_CONTENTION: 'CONFLICT',
  TEMPORARY_FAILURE: 'TIMEOUT',
  PLAN_NOT_RECORDABLE: 'BAD_REQUEST',
  COMMAND_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Entry Transaction関連 =====
  CREATE_WITH_TAGS_FAILED: 'INTERNAL_SERVER_ERROR',
  UPDATE_WITH_TAGS_FAILED: 'INTERNAL_SERVER_ERROR',
  DELETE_WITH_CLEANUP_FAILED: 'INTERNAL_SERVER_ERROR',
  RPC_CALL_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== User関連 =====
  EXPORT_FAILED: 'INTERNAL_SERVER_ERROR',
  PROFILE_UPDATE_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Reflection関連 =====
  QUOTA_EXCEEDED: 'FORBIDDEN',
  INSUFFICIENT_DATA: 'BAD_REQUEST',
  API_KEY_MISSING: 'INTERNAL_SERVER_ERROR',
  GENERATION_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Badge関連 =====
  EVALUATE_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Contact関連 =====
  CONTACT_DELIVERY_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Billing関連 =====
  STRIPE_NOT_CONFIGURED: 'INTERNAL_SERVER_ERROR',
  CHECKOUT_FAILED: 'INTERNAL_SERVER_ERROR',
  PORTAL_FAILED: 'INTERNAL_SERVER_ERROR',
  SUBSCRIPTION_NOT_FOUND: 'NOT_FOUND',
  BILLING_ACCOUNT_CLOSING: 'CONFLICT',
  BILLING_CHECKOUT_NOT_AVAILABLE: 'CONFLICT',
  BILLING_OPERATION_CONFLICT: 'CONFLICT',
  BILLING_OPERATION_INVALIDATED: 'CONFLICT',
  BILLING_RECOVERY_EXHAUSTED: 'CONFLICT',
  BILLING_RESPONSE_EXPIRED: 'CONFLICT',

  // ===== 外部カレンダー関連 =====
  SYNC_FAILED: 'INTERNAL_SERVER_ERROR',
  CONNECTION_NOT_FOUND: 'NOT_FOUND',
  // 接続が失効し再認証が必要。ユーザー起因の想定内状態なので 500 ではなく 409 にする。
  REAUTH_REQUIRED: 'CONFLICT',
  PROVIDER_UNAVAILABLE: 'INTERNAL_SERVER_ERROR',

  // ===== MCP connection 関連 =====
  REVOKE_FAILED: 'INTERNAL_SERVER_ERROR',
};
