/** tRPCエラーコードの型定義 */
export type TRPCErrorCode =
  'INTERNAL_SERVER_ERROR' | 'NOT_FOUND' | 'BAD_REQUEST' | 'FORBIDDEN' | 'UNAUTHORIZED' | 'CONFLICT';

/** サービスエラーコードとtRPCエラーコードのマッピング。 */
export const ERROR_CODE_MAP: Record<string, TRPCErrorCode> = {
  // ===== 共通エラー =====
  FETCH_FAILED: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CREATE_FAILED: 'INTERNAL_SERVER_ERROR',
  COMMAND_FAILED: 'INTERNAL_SERVER_ERROR',
  UPDATE_FAILED: 'INTERNAL_SERVER_ERROR',
  DELETE_FAILED: 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED: 'BAD_REQUEST',
  INVALID_INPUT: 'BAD_REQUEST',

  // ===== 認証・認可エラー =====
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_PASSWORD: 'UNAUTHORIZED',
  RECOVERY_EXHAUSTED: 'BAD_REQUEST',
  RECOVERY_INVALID: 'BAD_REQUEST',
  RECOVERY_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Tag関連 =====
  DUPLICATE_NAME: 'BAD_REQUEST',
  MERGE_FAILED: 'INTERNAL_SERVER_ERROR',
  SAME_TAG_MERGE: 'BAD_REQUEST',
  TARGET_NOT_FOUND: 'NOT_FOUND',
  UNGROUP_CONFLICTS: 'BAD_REQUEST',
  GROUP_NAME_CONFLICT: 'BAD_REQUEST',

  // ===== Tag並び替え関連 =====
  REORDER_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Palette関連 =====
  PIN_FAILED: 'INTERNAL_SERVER_ERROR',
  UNPIN_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== History関連 =====
  FETCH_PINNED_FAILED: 'INTERNAL_SERVER_ERROR',
  FETCH_ENTRIES_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Entry関連 =====
  TAG_FILTER_FAILED: 'INTERNAL_SERVER_ERROR',
  TIME_OVERLAP: 'BAD_REQUEST',
  UNPLANNED_IN_FUTURE: 'BAD_REQUEST',
  RECORD_IN_FUTURE: 'BAD_REQUEST',
  ALREADY_RECORDED: 'BAD_REQUEST',
  PLAN_IN_PAST: 'BAD_REQUEST',
  PLAN_TIME_LOCKED: 'BAD_REQUEST',
  SKIP_IN_FUTURE: 'BAD_REQUEST',
  INVALID_TIME_RANGE: 'BAD_REQUEST',
  INVALID_ENTRY_SHAPE: 'BAD_REQUEST',
  RESTORE_FAILED: 'INTERNAL_SERVER_ERROR',
  CONFLICT: 'CONFLICT',

  // ===== Entry Transaction関連 =====
  CREATE_WITH_TAGS_FAILED: 'INTERNAL_SERVER_ERROR',
  UPDATE_WITH_TAGS_FAILED: 'INTERNAL_SERVER_ERROR',
  DELETE_WITH_CLEANUP_FAILED: 'INTERNAL_SERVER_ERROR',
  RPC_CALL_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== User関連 =====
  EXPORT_FAILED: 'INTERNAL_SERVER_ERROR',
  PROFILE_UPDATE_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Reflection関連 =====
  QUOTA_EXCEEDED: 'FORBIDDEN',
  INSUFFICIENT_DATA: 'BAD_REQUEST',
  API_KEY_MISSING: 'INTERNAL_SERVER_ERROR',
  GENERATION_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Badge関連 =====
  EVALUATE_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Contact関連 =====
  CONTACT_DELIVERY_FAILED: 'INTERNAL_SERVER_ERROR',

  // ===== Billing関連 =====
  STRIPE_NOT_CONFIGURED: 'INTERNAL_SERVER_ERROR',
  CHECKOUT_FAILED: 'INTERNAL_SERVER_ERROR',
  PORTAL_FAILED: 'INTERNAL_SERVER_ERROR',
  SUBSCRIPTION_NOT_FOUND: 'NOT_FOUND',
};
