import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import {
  AUTH_EMAIL_TEMPLATES,
  generateProductAuthEmailTemplate,
  syncAuthEmailTemplates,
} from '../sync-auth-email-templates';

const repositoryRoot = resolve(import.meta.dirname, '../..');
const temporaryDirectories: string[] = [];

function createTemplateFixtureRoot(): string {
  const fixtureRoot = mkdtempSync(join(tmpdir(), 'dayopt-auth-email-sync-'));
  temporaryDirectories.push(fixtureRoot);

  for (const template of AUTH_EMAIL_TEMPLATES) {
    const sourcePath = resolve(fixtureRoot, template.source);
    mkdirSync(dirname(sourcePath), { recursive: true });
    writeFileSync(sourcePath, readFileSync(resolve(repositoryRoot, template.source), 'utf8'));
  }

  return fixtureRoot;
}

afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) {
    rmSync(directory, { force: true, recursive: true });
  }
});

describe('sync-auth-email-templates', () => {
  it('Deno template imports are converted for the Product preview runtime', () => {
    const source = `import { Html } from '@react-email/components';
import * as styles from './styles.tsx';

const i18n = {
  en: { ignoreLine: (appUrl: string) => 'Ignore this email.' },
  ja: { ignoreLine: (appUrl: string) => 'このメールを無視してください。' },
};

export function ConfirmEmail() {
  return <Html style={styles.main} />;
}
`;
    const template = AUTH_EMAIL_TEMPLATES.find(
      (candidate) => candidate.componentName === 'ConfirmEmail',
    );

    expect(template).toBeDefined();
    const generated = generateProductAuthEmailTemplate(source, template!);

    expect(generated).toContain("from 'react-email';");
    expect(generated).toContain("from './auth-email-styles.generated';");
    expect(generated).toContain('ignoreLine: (_appUrl: string) =>');
    expect(generated).not.toContain('ignoreLine: (appUrl: string) =>');
    expect(generated).toContain('export default ConfirmEmail;');
    expect(generated).toContain('Do not edit this file directly.');
  });

  it('styles stay byte-equivalent apart from the generated header', () => {
    const source = `import type { CSSProperties } from 'react';

export const main: CSSProperties = { backgroundColor: '#fafafa' };
`;
    const template = AUTH_EMAIL_TEMPLATES.find((candidate) => candidate.kind === 'styles');

    expect(template).toBeDefined();
    const generated = generateProductAuthEmailTemplate(source, template!);

    expect(generated).toContain(source.trimEnd());
    expect(generated).not.toContain('export default');
  });

  it('fails closed when a required runtime import changes', () => {
    const template = AUTH_EMAIL_TEMPLATES.find(
      (candidate) => candidate.componentName === 'MagicLinkEmail',
    );

    expect(template).toBeDefined();
    expect(() =>
      generateProductAuthEmailTemplate('export function MagicLinkEmail() {}', template!),
    ).toThrow('Expected canonical template fragment was not found');
  });

  it('fails closed when a Product-only parameter adapter no longer matches', () => {
    const template = AUTH_EMAIL_TEMPLATES.find(
      (candidate) => candidate.componentName === 'PasswordResetEmail',
    );
    const source = `import { Html } from '@react-email/components';
import * as styles from './styles.tsx';

export function PasswordResetEmail() {
  return <Html style={styles.main} />;
}
`;

    expect(template).toBeDefined();
    expect(() => generateProductAuthEmailTemplate(source, template!)).toThrow(
      'Expected 2 canonical template fragments, found 0: securityNote: (appUrl: string) =>',
    );
  });

  it('detects all drift, restores generated files, and is idempotent', () => {
    const fixtureRoot = createTemplateFixtureRoot();
    const expectedDestinations = AUTH_EMAIL_TEMPLATES.map(({ destination }) => destination);

    expect(syncAuthEmailTemplates({ check: true, rootDir: fixtureRoot })).toEqual(
      expectedDestinations,
    );

    syncAuthEmailTemplates({ rootDir: fixtureRoot });
    expect(syncAuthEmailTemplates({ check: true, rootDir: fixtureRoot })).toEqual([]);

    for (const template of AUTH_EMAIL_TEMPLATES) {
      const destinationPath = resolve(fixtureRoot, template.destination);
      writeFileSync(destinationPath, `${readFileSync(destinationPath, 'utf8')}manual drift\n`);
    }
    expect(syncAuthEmailTemplates({ check: true, rootDir: fixtureRoot })).toEqual(
      expectedDestinations,
    );

    syncAuthEmailTemplates({ rootDir: fixtureRoot });
    const firstSync = AUTH_EMAIL_TEMPLATES.map(({ destination }) =>
      readFileSync(resolve(fixtureRoot, destination), 'utf8'),
    );
    syncAuthEmailTemplates({ rootDir: fixtureRoot });
    const secondSync = AUTH_EMAIL_TEMPLATES.map(({ destination }) =>
      readFileSync(resolve(fixtureRoot, destination), 'utf8'),
    );

    expect(secondSync).toEqual(firstSync);
  });
});
