-- entry_tags統合マイグレーション（20260415000000）の前処理
-- 戻り値型が変わる関数をDROPしておく（CREATE OR REPLACEでは型変更不可のため）

DROP FUNCTION IF EXISTS public.get_tag_cumulative_time(UUID, UUID, TEXT, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_tag_avg_fulfillment(UUID, UUID, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_tag_plan_rate(UUID, UUID, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_tag_hourly_distribution(UUID, UUID, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_tag_dow_distribution(UUID, UUID, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_child_tag_breakdown(UUID, UUID, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_tag_fulfillment_distribution(UUID, UUID, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_tag_accuracy_trend(UUID, UUID, TEXT, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_tag_recent_entries(UUID, UUID, INT);
DROP FUNCTION IF EXISTS public.get_estimation_accuracy(UUID, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_context_switches(UUID, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_time_by_tag(UUID, TEXT, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_tag_stats(UUID);
DROP FUNCTION IF EXISTS public.merge_tags(UUID, UUID, UUID);
DROP FUNCTION IF EXISTS public.get_weekly_focus_score(UUID, INT);
DROP FUNCTION IF EXISTS public.get_stats_kpi_summary(UUID, TIMESTAMPTZ, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_time_pl_data(UUID, TIMESTAMPTZ, TIMESTAMPTZ, TEXT);
DROP FUNCTION IF EXISTS public.get_stats_page_data(UUID, TIMESTAMPTZ, TIMESTAMPTZ);
